instrumentation:
    root: ./src
    default-excludes: true
    include-all-sources: true
reporting:
    print: summary
    reports:
        - html
    dir: ./reports/coverage/report-html
    watermarks:
        statements: [50, 80]
        lines: [50, 80]
        functions: [50, 80]
        branches: [50, 80]
